<?php
/**
 * @category   Clarksfield
 * @package    Clarksfield_Customersspeak
 * @author     nitish.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Clarksfield\Customersspeak\Model\ResourceModel;

class Customersspeak extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('clarksfield_customersspeak', 'customersspeak_id');   //here "clarksfield_customersspeak" is table name and "customersspeak_id" is the primary key of custom table
    }
}