<?php
$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $objectManager->create('Magento\Framework\Pricing\Helper\Data');
$listBlock = $objectManager->get('\Magento\Catalog\Block\Product\ListProduct');
$product1 = $objectManager->get('Magento\Framework\Registry')->registry('current_product');//get current product
$relatedProducts = $product1->getRelatedProducts();
$obj = \Magento\Framework\App\ObjectManager::getInstance();
 ?>
<!-- begin product-wrap-->
			<?php if (!empty($relatedProducts)) { ?>   
			    <div class="products wrapper">
			        <div class="list_img_wrap">
					<h3>Similar Tyres</h3>
						<?php 
						foreach ($relatedProducts as $relatedProduct) {
        				$product1 = $objectManager->create('Magento\Catalog\Model\Product')->load($relatedProduct->getId()); 
        				$pname=$product1->getName();
					     $productprice=$product1->getPrice();
					     $producturl=$product1->getProductUrl();
					     $psdescription=$product1->getShortDescription();
					     $formattedPrice = $priceHelper->currency($productprice, true, false);
					    $imageUrl = $this->getUrl().'pub/media/catalog/product'.$product1->getImage();
					     $addToCartUrl =  $listBlock->getAddToCartUrl($product1);
        				?>
							 <div class="col-md-4">
                <div class="list_inner">
                    <div class="wranty_sec">
                              <?php

                                 $warranty_attribute = $product1->getResource()->getAttribute('warranty_period');
	
                                        if ($warranty_attribute){
                                        // Get Value
                                        $warranty_value = $warranty_attribute->getFrontend()->getValue($product1);
                                        if($warranty_value)
                                        {
						echo "$warranty_value Years Warranty";
                                        }else{
                                            echo "No info available";
                                        }
                                        
                                        }?>
                            </div>
                    <?php // Product Image ?>
                    <div class="image_sec">
                    <a href="<?php echo $producturl; ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <img src="<?php echo $imageUrl;  ?>">
                    </a>
                    </div>
                    <div class="rating_sec">
                                <ul>
                                    <li><a href="#"><?php
                                        $productRepository = $obj->get('\Magento\Catalog\Model\ProductRepository');
                                        $product = $productRepository->get($product1->GetSku());
                                        $brand_type = $product->getProductBrand();
                                        $attr = $product1->getResource()->getAttribute('product_brand');
                                        
                                       if ($attr->getSource()->getOptionText($brand_type) !== '-- Please Select --') {

                                             echo $attr->getSource()->getOptionText($brand_type);
                                        }   
                                         ?></a></li>
                                    <li> 
                                        <?php if ($product1->getRatingSummary()): ?>
                                    <?php echo $block->getReviewsSummaryHtml($product1, $templateType, true); ?>
                                    <?php else: ?>
                                    <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                    <span class="label"><span>Rating:</span></span>
                                    <div class="rating-result" title="0%">
                                    <span style="width:0%"><span>0%</span></span>
                                    </div>
                                    </div>
                                    <div class="reviews-actions">
                                    (0)
                                    </div>
                                    </div>
                                    <?php endif; ?>
                                    </li>

                                    </ul>
                            </div>
                     <?php
                            $_productNameStripped = $block->stripTags($product1->getName(), null, true);
                        ?>    
                            <div class="tittle_head">
                                <a class="product-item-link"
                               href="<?php echo $producturl; ?>">
                                <h3><?php echo $pname; ?></h3>
                                 </a>
                            </div>
                            <div class="amout_sec">
                                <ul>
                                    <li><a href="<?= $block->escapeUrl($product1->getProductUrl()) ?>">
                                        <?= /* @noEscape */ $block->getProductPrice($product1) ?>
                                        <?= $block->getProductDetailsHtml($product1) ?></a></li>
                                    <li><a href="<?= $block->escapeUrl($product1->getProductUrl()) ?>" ><button class=view_detail> View Details</button></a></li>
                                </ul>
                            </div>
                </div>
            </div>
					<?php } ?>
			<!-- finish product-wrap -->
			</div>
</div>
			<?php } ?>
              <!-- <div class="col-md-12">
                 <h1 class="page-bottom_title">FAQ</h1>
                 <div class="accordion">
                     <div class="accordion-item">
                     <div class="accordion-item-header">
                    Q1..When will my order for tyres reach my location?
                  </div>

                  <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
                                <p>Ans.1 We have experts with tyre changing equipment in the Tyresnmore Vans and they will reach your location , in Hyderabad , Bangalore , Delhi NCR to change tyres at your doorstep.</p>
                                <p>Orders placed before 3 PM will be fulfilled today*
                                Orders placed after 3 PM will be fulfilled tomorrow
                                *The order fulfillment on same day is subject to availability of tyres in our warehouse. Our team will call you to fix an appointment for changing tyres at your location.</p>

                                <p>For cities other than those mentioned above , our tyre experts will inform you about the time of delivery and additional shipping charges if any.</p>
                               </div>
                             </div>
                   </div>
                   <div class="accordion-item">
                     <div class="accordion-item-header">
                    Q2.How long does it take to change tyres?
                  </div>

                  <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
                                <p>Ans2.Once our team reaches your location we need parking space for our van next to your vehicle , we have the equipment to change 1 tyre in 20 to 30 minutes and up 
                                to 4 tyres in 30 to 60 minutes</p>
                               </div>
                             </div>
                   </div>
                   <div class="accordion-item">
                     <div class="accordion-item-header">
                    Q3.What are the Payment options , can I pay on delivery or through EMIs?
                  </div>

                  <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
                                <p>You can:</p>
                                <p>Pay on delivery *</p>
                                <p>Easy EMI available</p>
                                <p>Pay 100 % online now</p>
                                <p>*TnM reserves the right to ask for partial or full advance payment for any orders</p>
                               </div>
                             </div>
                   </div>
                   <div class="accordion-item">
                     <div class="accordion-item-header">
                   Q4.Will the tyre experts come to my location with debit/credit card machine , in case I am paying on delivery?
                  </div>

                  <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
                                <p>Ans.4 Yes the tyre experts will come with debit/credit card machine to your location to enable you to make payment,alternatively you can also pay via cash on delivery.
                                Tyresnmore online private ltd. reserves the right to receive partial or full advance payment for any orders.</p>
                               </div>
                             </div>
                   </div>
                   <div class="accordion-item">
                     <div class="accordion-item-header">
                    Q5.How do I get my tyre manufacturer warranty registered?
                  </div>

                  <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
                                <p>You can speak to our tyre expert on 92.1275.1275 , and they will guide you to get the tyre manufacturer's warranty registered.</p>
                               </div>
                             </div>
                   </div>
                       
                    </div>
                 </div> -->
			<!-- finish content -->
				