<?php
/**
 * @category   Tyresclarksfield
 * @package    Tyresclarksfield_Testimonials
 * @author     mukesh.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tyresclarksfield\Testimonials\Block;

use Magento\Framework\View\Element\Template\Context;
use Tyresclarksfield\Testimonials\Model\TestimonialsFactory;
/**
 * Testimonials List block
 */
class TestimonialsListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Testimonials
     */
    protected $_testimonials;
    public function __construct(
        Context $context,
        TestimonialsFactory $testimonials
    ) {
        $this->_testimonials = $testimonials;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('                        '));
        
        if ($this->getTestimonialsCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'tyresclarksfield.testimonials.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getTestimonialsCollection()
            );
            $this->setChild('pager', $pager);
            $this->getTestimonialsCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getTestimonialsCollection()
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 25;

        $testimonials = $this->_testimonials->create();
        $collection = $testimonials->getCollection();
        $collection->addFieldToFilter('status','1');
        //$testimonials->setOrder('testimonials_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}
