<div class="container category-section">
  <div class="row blog-section">
    <div class="col-md-4"></div>
    <div class="col-md-8">
      <div class="row">
         <div class="col-md-4 category-id"><a href="<?php echo $this->getUrl("blogs/category/uncategorized");?>"><span>Uncategorized</span></a></div>
         <div class="col-md-4 category-id"><a href="<?php echo $this->getUrl("blogs/category/tyre-information");?>"><span>Tyre Information</span></a></div>
         <div class="col-md-4 category-id"><a href="<?php echo $this->getUrl("blogs/category/car-information");?>"><span>Car Information</span></a></div>
      </div>
    </div>
  </div>
</div>