<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile
?>



<form class="form quickrfq"
      action="<?php  echo $block->getFormAction(); ?>"
      id="quickrfq_form"
      enctype="multipart/form-data"
      method="post"
      onsubmit="return myFunction2()"
      data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>"
      data-mage-init='{"validation":{}}'>


    <fieldset class="fieldset">
        <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('RFQ Requirements') ?></span></legend><br />
    <!--     <div class="field name required">
                <label class="label" for="company"><?php //echo __('Company Name:') ?></label>
                <div class="control">
                        <input name="company" id="company" value="" class="input-text" type="text" data-validate="{required:true}"/>
                </div>
	</div> -->
        <div class="field contact_name required">
            <label class="label" for="contact_name"><span><?php /* @escapeNotVerified */ echo __('Name') ?></span></label>
            <div class="control">
                <input name="contact_name" id="contact_name" title="<?php /* @escapeNotVerified */ echo __('Contact Name') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserName()) ?>" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>
        <div class="field email">
            <label class="label" for="email"><span><?php /* @escapeNotVerified */ echo __('Email') ?></span></label>
            <div class="control">
                <input name="email" id="email@123" title="<?php /* @escapeNotVerified */ echo __('Email') ?>" value="<?php echo $block->escapeHtml($this->helper('Magento\Contact\Helper\Data')->getUserEmail()) ?>" class="input-text" type="email" />
                <!-- data-validate="{required:true, 'validate-email':true}" -->
            </div>
        </div>
        <div class="field phone required">
            <label class="label" for="phone"><span><?php /* @escapeNotVerified */ echo __('Mobile Number') ?></span></label>
            <div class="control">
                <input name="phone" id="phone" title="<?php /* @escapeNotVerified */ echo __('Phone Number') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/>
            </div>
        </div>

          <div class="field city required">
            <label class="label" for="city"><span><?php /* @escapeNotVerified */ echo __('City') ?></span></label>
            <div class="control">
              <!--   <input name="city" id="city" title="<?php /* @escapeNotVerified */ echo __('City') ?>" value="" class="input-text" type="text" data-validate="{required:true}"/> -->
              <select name="city" class="input-text" data-validate="{required:true}"/>
                            <option selected="" value="">Select city</option>
                                <option value="Delhi">Delhi</option>
                                <option value="Faridabad">Faridabad</option>
                                <option value="Gurugram">Gurugram</option>
                                <option value="Ghaziabad">Ghaziabad</option>
                                <option value="Noida">Noida</option>
                                <option value="Bengaluru">Bengaluru</option>
                                <option value="Mumbai">Mumbai</option>
                                <option value="Navi Mumbai">Navi Mumbai</option>
                                <option value="Thane">Thane</option>
                                <option value="Vashi">Vashi</option>
                                <option value="Pune">Pune</option>
                                <option value="Pimpri Chinchwad">Pimpri Chinchwad </option>
                                <option value="Hyderabad">Hyderabad</option>
                                <option value="Secundrabad">Secundrabad</option>
                                <option value="Chennai">Chennai</option>
                    </select>
            </div>
        </div>
        <div class="field project_title">
            <label class="label" for="project_title"><span><?php /* @escapeNotVerified */ echo __('Product Name') ?></span></label>
            <div class="control">
                <input name="project_title" id="project_title" title="<?php /* @escapeNotVerified */ echo __('Project Title') ?>" value="" class="input-text" type="text" readonly/>
            </div>
        </div>
        <!-- <div class="field date">
            <label class="label" for="date"><span><?php /* @escapeNotVerified */ //echo __('Quote Needed By') ?></span></label>
            <div class="control">
                <input name="date" id="date" title="<?php /* @escapeNotVerified */ //echo __('Quote Needed By') ?>" value="" class="hasDatepicker" type="text" />

            </div>
        </div> -->

        <?php //$_date = $block->getLayout()->createBlock('FME\Quickrfq\Block\Widget\DateQuote') ?>
        <?php //if ($_date->isEnabled()): ?>
            <?php //echo $_date->toHtml() ?>
        <?php //endif ?>

        <!-- <div class="field budget">
			    <label for="budget"><?php //echo __('Project Budget Status') ?></label>
			    <div class="input-box">
			       <input name="budget" value="Approved" checked="checked" type="radio"><?php //echo __('Approved') ?>
			       <input name="budget" value="Approval Pending" type="radio"><?php //echo __('Approval Pending') ?>
			       <input name="budget" value="Open" type="radio"><?php //echo __('Open') ?>
			       <input name="budget" value="No Approval" type="radio"><?php //echo __('No Approval') ?>
			    </div>
        </div> -->

        <!-- <div class="field overview required">
            <label class="label" for="overview"><span><?php /* @escapeNotVerified */ //echo __('Brief Overview') ?></span></label>
            <div class="control">
                <textarea name="overview" id="overview" title="<?php /* @escapeNotVerified */ //echo __('Brief Overview') ?>" class="input-text" cols="5" rows="3" data-validate="{required:true}"></textarea>
            </div>
        </div> -->





        <!-- <div class="field prd">
			    <label for="prd"><?php //echo __('Upload Document:') ?></label>
			    <div class="input-box">
				<input type="file" id="prd" name="prd">
				<br>
				  <p> <?php //echo __("You can upload files with these file extensions only (%1)", $block->getAllowedFileExtensions()) ?> </p>
			    </div>
        </div> -->

        <div class="field">

                <?php if($block->isCaptchaEnable()): ?>
                       <div class="g-recaptcha"  name="recaptcha" id="recaptcha" data-sitekey="<?php echo $block->getPublicKey(); ?>"></div>
                    <div ><p style="
    cursor: auto;
    /* text-decoration: underline; */
    color: #9b9b9b;
    padding-left: 235px;
    font-family: Roboto,helvetica,arial,sans-serif;
    font-size: 8px;
    font-weight: 400;
    margin-top: -35px;
">by <a style="color: #9b9b9b;" rel="no-follow" target="_Blank" href="https://www.fmeextensions.com/request-for-quote-magento-2.html">Fmeextensions</a></p>  </div>
                                                  <br>


                <?php endif; ?>
        </div>




        <?php echo $block->getChildHtml('form.additional.info'); 
          ?>
    </fieldset>
    <div class="actions-toolbar">
        <div class="primary">
            <input type="hidden" name="hideit" id="hideit" value="" />
            <button type="submit" title="<?php echo __('Submit') ?>" class="action submit primary">
                <span><?php /* @escapeNotVerified */ echo __('Submit') ?></span>
            </button>
        </div>
    </div>
</form>

<script type="text/javascript">
    function myFunction2() {
        var exists = document.getElementById("g-recaptcha-response");

            if(exists == null){
                    
            }
        
             else{

            var check = document.getElementById("g-recaptcha-response").value;
           // alert(check);
                if(check=='' || check == null){
                    document.getElementById("recaptcha").style.border = "1px solid #ea0e0e";
                    return false;
                }
                else{
                    document.getElementById("recaptcha").style.border = "none";
                    return true;
                }
            }
            
   
}
</script>
 <script src="https://www.google.com/recaptcha/api.js" async defer></script>


<style type="text/css">
    
    #recaptcha {
  display: inline-block;
  position: relative;
  
  
}
 .field label {
    color: #000;
    font-size: 14px;
    padding-left: 0px;
    font-weight: 600;
}
   
.modal-popup .modal-header {
    border-bottom: none;
}
.modal-popup._inner-scroll .modal-content {
    box-shadow: none;
    border-top: none;
}

</style>