<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */
?>

<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>
<!-- <script>
require(['jquery', 'jquery/ui'], function($){
    $(document).ready(function(){
    $(".opc-wrapper").prepend( $(".opc-progress-bar") );
    });
});
</script> -->


<?php 
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
    $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $storeID       = $storeManager->getStore()->getStoreId(); 
    $storeName     = $storeManager->getStore()->getName();
        $session = $objectManager->get('Magento\Customer\Model\Session');
?>

<script src="https://tyresnmore.com/phonepe-js-sdk-master/bundle.js"></script>
<script>
require(['jquery','jquery/jquery.cookie'],
  function($){
    $('document').ready(function(){

    $("#VWGFGAW").val("<?=$session->getTestKey(); ?>");

    var date = new Date();
    var minutes = 15;
    date.setTime(date.getTime() + (minutes * 60 * 1000));


    var  storeID="<?=$storeID;?>";

     if(storeID==6){

    if($.cookie('phonepe')!=1){
        $.cookie('phonepe', '1',{expires: date , path: '/'});


        //alert(storeID);





        window.PhonePe.PhonePe.build(window.PhonePe.Constants.Species.web).then((sdk) => {
                        sdk.fetchAuthToken().then((res) => {



                          $.ajax({
                                type: 'POST',
                                url: '/phonepe/payment/accessToken',
                                data: {'grantToken':res.grantToken} ,
                                success: function (response) {

                                   window.location.reload(true);

                                },
                                error: function (response) {



                                }
                            });


                        }).catch((err) => {
                            window.location.href='/customer/account/login/';


                        });

                });

        };

      };
    });
});
</script>

