<?php
/**
 * @category   Tyresclarksfield
 * @package    Tyresclarksfield_Testimonials
 * @author     mukesh.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tyresclarksfield\Testimonials\Model\ResourceModel;

class Testimonials extends \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    /**
     * Define main table
     */
    protected function _construct()
    {
        $this->_init('tyresclarksfield_testimonials', 'testimonials_id');   //here "tyresclarksfield_testimonials" is table name and "testimonials_id" is the primary key of custom table
    }
}