<div class="faq_list_wraper">
    <div class="container-fluid">
   <div class="page-bottom pgae_b_new">
         <div class="row">
            <div class="col-md-12">
               <h4 class="page-bottom_title_new">FAQ</h4>
               <?php
                     echo $this->getLayout()->createBlock("Tyres\Faq\Block\FaqListData")->setTemplate("Magento_Theme::html/Faq/list.phtml")->toHtml();
                     ?>
            </div>
         </div>
    </div>
</div>
</div>
