<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
use Magento\Framework\App\Action\Action;

?>
<?php
// phpcs:disable Magento2.Templates.ThisInTemplate.FoundThis

/**
 * Product list template
 *
 * @var $block \Magento\Catalog\Block\Product\ListProduct
 */
?>
<?php
$obj = \Magento\Framework\App\ObjectManager::getInstance();
$_productCollection = $block->getLoadedProductCollection();
$_helper = $this->helper(Magento\Catalog\Helper\Output::class);
$_imagehelper = $this->helper('Magento\Catalog\Helper\Image');
// $_category_config = $this->helper('Smartwave\Porto\Helper\Data')->getConfig('porto_settings/category');

$productData=array();
$product_count=0;

?>
<?php if (!$_productCollection->count()) :?>
    <div class="message info empty"><div><?= $block->escapeHtml(__('We can\'t find products matching the selection.')) ?></div></div>
<?php else :?>
    <?= $block->getToolbarHtml() ?>
    <?= $block->getAdditionalHtml() ?>
    <?php
    if ($block->getMode() == 'grid') {
        $viewMode = 'grid';
        $imageDisplayArea = 'category_page_grid';
        $showDescription = false;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::SHORT_VIEW;
    } else {
        $viewMode = 'list';
        $imageDisplayArea = 'category_page_list';
        $showDescription = true;
        $templateType = \Magento\Catalog\Block\Product\ReviewRendererInterface::FULL_VIEW;
    }
    
    $image_width = 300;
    $image_height = 300;
    $iterator = 1;
    /**
     * Position for actions regarding image size changing in vde if needed
     */
    $pos = $block->getPositioned();
    ?>    
    <div class="row mproduct">
    <div class="mobile_product_description_1">
    <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('mobile_product_description')->toHtml();?>
    </div>
    <div class="col-md-8">    
    <div class="products wrapper <?= /* @noEscape */ $viewMode ?> products-<?= /* @noEscape */ $viewMode ?>">
        <div class="list_img_wrap">
            <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
            <?php foreach ($_productCollection as $_product) :
                ?>
                
                <?php
                // if($_category_config['aspect_ratio'])
                //     $productImage = $_imagehelper->init($_product, $image)->constrainOnly(FALSE)->keepAspectRatio(TRUE)->keepFrame(FALSE)->resize($image_width);
                // else
                $productImage = $_imagehelper->init($_product, $imageDisplayArea)->resize($image_width, $image_height);
                $productImageUrl = $productImage->getUrl();
                
               $p_image=$productImageUrl;
               $p_url=$_product->getProductUrl();
               $p_name=$_helper->productAttribute($_product, $_product->getName(), 'name');
               $p_price=$_product->getPrice();
            //   $product =["@type" => "ListItem","position"=>$iterator,"item"=>["@type" => "Product","image"=>$p_image,"url"=>$p_url,"name"=>$p_name,"offers"=>["@type"=>"Offer","price"=>$p_price,"priceCurrency"=>"INR"]]];

               $product =["@type" => "ListItem","position"=>$iterator,"image"=>$p_image,"url"=>$p_url,"name"=>$p_name];

               array_push($productData,$product);
               
               $iterator++ == 1;
            ?>
            <div class="col-md-4">
                <div class="list_inner" data-container="product-<?= /* @noEscape */ $viewMode ?>">
                    <div class="wranty_sec">
                              <?php

                                 $warranty_attribute = $_product->getResource()->getAttribute('warranty_period');
	
                                        if ($warranty_attribute){
                                        // Get Value
                                        $warranty_value = $warranty_attribute->getFrontend()->getValue($_product);
                                        if($warranty_value)
                                        {
						echo "$warranty_value Years Warranty";
                                        }else{
                                            echo "No info available";
                                        }
                                        
                                        }?>
                            </div>
                    <?php
                    $productImage = $block->getImage($_product, $imageDisplayArea);
                    if ($pos != null) {
                        $position = ' style="left:' . $productImage->getWidth() . 'px;'
                            . 'top:' . $productImage->getHeight() . 'px;"';
                    }
                    ?>
                    <?php // Product Image ?>
                    <div class="image_sec">
                    <a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>"
                       class="product photo product-item-photo"
                       tabindex="-1">
                        <?= $productImage->toHtml() ?>
                    </a>
                    </div>
                    <div class="rating_sec">
                                <ul>
                                    <li><a href="#"><?php
                                        $productRepository = $obj->get('\Magento\Catalog\Model\ProductRepository');
                                        $product = $productRepository->get($_product->GetSku());
                                        $brand_type = $product->getProductBrand();
                                        $attr = $_product->getResource()->getAttribute('product_brand');
                                        
                                       if ($attr->getSource()->getOptionText($brand_type) !== '-- Please Select --') {

                                             echo $attr->getSource()->getOptionText($brand_type);
                                        }   
                                         ?></a></li>
                                    <li> 
                                    <?php //if ($_product->getRatingSummary()): ?>
                                    <?php //echo $block->getReviewsSummaryHtml($_product, $templateType, true); ?>
                                    <?php //else: ?>
                                    <!-- <div class="product-reviews-summary short">
                                    <div class="rating-summary">
                                    <span class="label"><span>Rating:</span></span>
                                    <div class="rating-result" title="0%">
                                    <span style="width:0%"><span>0%</span></span>
                                    </div>
                                    </div>
                                    <div class="reviews-actions">
                                    (0)
                                    </div>
                                    </div> -->
                                    <?php //endif; ?>
                                    </li>

                                    </ul>
                            </div>
                     <?php
                            $_productNameStripped = $block->stripTags($_product->getName(), null, true);
                        ?>    
                            <div class="tittle_head">
                                <a class="product-item-link"
                               href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                <h3><?= /* @noEscape */ $_helper->productAttribute($_product, $_product->getName(), 'name') ?></h3>
                                 </a>
                            </div>
                            <div class="amout_sec">
                                <ul>
                                    <li><a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>">
                                        <?= /* @noEscape */ $block->getProductPrice($_product) ?>
                                        <?= $block->getProductDetailsHtml($_product) ?></a></li>
                                    <li><a href="<?= $block->escapeUrl($_product->getProductUrl()) ?>" ><button class=view_detail> View Details</button></a></li>
                                </ul>
                            </div>
                </div>
            </div>
            <?php endforeach; 
            
             
            $product_Data=json_encode($productData);
            $product_count= count($_productCollection); 
            
            if(isset($_SERVER['HTTPS']) &&  $_SERVER['HTTPS'] === 'on'){
                $link = "https"; 
            }else{
                $link = "http"; 
            }        
            $link .= "://"; 
            $link .= $_SERVER['HTTP_HOST']; 
            $link .= $_SERVER['REQUEST_URI']; 
            $url=$link;  
            
          
            ?>
            
            <script type="application/ld+json">

               {"@context": "http://schema.org",
               "@type": "ItemList",
               "name":"<?php echo $this->getLayer()->getCurrentCategory()->getName().' Tyre Price';?>",
               "url": "<?php echo $url; ?>",
               "numberOfItems":"<?php echo $product_count; ?>", 
               "itemListElement": <?php echo $product_Data; ?>}
           </script>
        </div>
    </div>
       <?= $block->getToolbarHtml() ?>
</div>

        <?php
            $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
            $category      = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
            if($category){
          ?> 
    <div class="col-md-4">
     <div class="right_sidebar_wraper">
          <div class="rsidebar_tittle_1">              
                <!--<h3>You can check Tyre size of <?php // echo $category->getName(); ?> </h3> -->
                   <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
                                                ->setBlockId('check_Tyre_size_of_Linea_Tjet_plus')->toHtml();?>
            </div>
            <div class="rsidebar_tittle_1 important_sec">
                <h3>Important</h3>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Important')->toHtml();?> 
            </div>
        </div>
<div class="rsidebar_tittle_1 important_sec">
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId($category->getName())->toHtml();?>
            </div>
     </div>
<?php }else if($_productCollection->getdata()[0]['manufacturer_value']){ ?>
    
    <div class="col-md-4">
     <div class="right_sidebar_wraper">
          <div class="rsidebar_tittle_1">              
                <!-- <h3>You can check Tyre size of <?php // echo $_productCollection->getdata()[0]['manufacturer_value']; ?> </h3> -->
                   <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')
                                                ->setBlockId('check_Tyre_size_of_Linea_Tjet_plus')->toHtml();?>
            </div>
            <div class="rsidebar_tittle_1 important_sec">
                <h3>Important</h3>
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('Important')->toHtml();?> 
            </div>
        </div>
     </div>

    <?php } ?>
           <div id="popup-mpdal" >
                <?php echo $this->getLayout()->createBlock('Magento\Cms\Block\Block')->setBlockId('pay-on-delivery')->toHtml();?>
          </div>
</div>
    <?php if (!$block->isRedirectToCartEnabled()) :?>
        <script type="text/x-magento-init">
        {
            "[data-role=tocart-form], .form.map.checkout": {
                "catalogAddToCart": {
                    "product_sku": "<?= $block->escapeJs($_product->getSku()) ?>"
                }
            }
        }
        </script>
    <?php endif; ?>
<?php endif; ?>
<script>
    require(
        [
            'jquery',
            'Magento_Ui/js/modal/modal'
        ],
        function(
            $,
            modal
        ) {
            var options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                buttons: [{
                    text: $.mage.__('Close'),
                    class: '',
                    click: function () {
                        this.closeModal();
                    }
                }]
            };

            var popup = modal(options, $('#popup-mpdal'));
            $("#click-me").on('click',function(){
                $("#popup-mpdal").modal("openModal");
            });

        }
    );
</script>
