<?php
/**
 * Category layered navigation
 *
 * @var $block \Magento\LayeredNavigation\Block\Navigation
 */
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance ();
    $categorys = $objectManager->get('Magento\Framework\Registry')->registry('current_category');
    $categoryFactory = $objectManager->get('\Magento\Catalog\Model\CategoryFactory');
    $category = $categoryFactory->create()->load($categorys->getId());
    $parentCategories = $category->getParentCategories();
    $alloychildcatId = array(); 
    foreach ($parentCategories as $cat){
    $alloychildcatId[] = $cat->getId();
}

?>
<?php if ($block->canShowBlock()) : ?>
<div class="row">
    <div class="col-md-12">
    <div class="block filter clearfix" id="layered-filter-block" data-mage-init='
    {
        "collapsible":
        {
            "openedState": "active",
            "collapsible": true,
            "active": false,
            "collateral":
            {
                "openedState": "filter-active",
                "element": "body"
            }
        }
    }'>
        <?php $filtered = count($block->getLayer()->getState()->getFilters()) ?>
      <div class="block-title filter-title clearfix" data-count="<?= /* @noEscape */ $filtered ?>">
         <?php if($_SERVER['SERVER_NAME'] == 'staging-new.tyresnmore.com') { ?>
               <?php if(in_array(4524, $alloychildcatId)) { ?>
           <strong data-role="title" class="btn-filter"><i class="fa fa-filter"></i> <?= $block->escapeHtml(__('Filter')); ?></strong>
           <?php } ?>
           <?php } else if($_SERVER['SERVER_NAME'] == 'tyresnmore.com'){ ?>
            <?php if(in_array(4766, $alloychildcatId)) { ?>
           <strong data-role="title" class="btn-filter"><i class="fa fa-filter"></i> <?= $block->escapeHtml(__('Filter')); ?></strong>
           <?php } ?>
           <?php } ?>
        </div>
        <div class="block-content filter-content clearfix">
            <?= $block->getChildHtml('state') ?>

            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear">
                        <span><?= $block->escapeHtml(__('Clear All')) ?></span>
                    </a>
                </div>
            <?php endif; ?>
            <?php $wrapOptions = false; ?>
            <?php foreach ($block->getFilters() as $filter) : ?>
                <?php if ($filter->getItemsCount()) : ?>
                    <?php if (!$wrapOptions) : ?>
                        <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle"><?= $block->escapeHtml(__('Shopping Options')) ?></strong>
                        <div class="filter-options" id="narrow-by-list" data-role="content" data-mage-init='
                        {
                            "accordion":
                            {
                                "openedState": "active",
                                "collapsible": true,
                                "active": false,
                                "multipleCollapsible": false
                            }
                        }'>
                        <?php $wrapOptions = true;
                        endif; ?>
                    <?php if ($filter->getItemsCount() && $filter->getName() != 'Category'): ?>
                    <div data-role="collapsible" class="filter-options-item">
                        <div data-role="title" class="filter-options-title" style="text-transform: capitalize;"><?= $block->escapeHtml(__($filter->getName())) ?></div>
                        <div data-role="content" class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></div>
                    </div>
                    <?php endif; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php if ($wrapOptions) : ?>
                </div>
            <?php else : ?>
                <script>
                    require([
                        'jquery'
                    ], function ($) {
                        $('#layered-filter-block').addClass('filter-no-options');
                    });
                </script>
            <?php endif; ?>
        </div>
    </div>
    </div>
</div>
<?php endif; ?>
