<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Checkout\Block\Onepage */
?>

<div>
    <h3 class="checkout-title">
        Checkout
    </h3>
</div>
<div id="checkout" data-bind="scope:'checkout'" class="checkout-container">
    <div id="checkout-loader" data-role="checkout-loader" class="loading-mask" data-mage-init='{"checkoutLoader": {}}'>
        <div class="loader">
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('images/loader-1.gif')) ?>"
                 alt="<?= $block->escapeHtmlAttr(__('Loading...')) ?>"
                 style="position: absolute;">
        </div>
    </div>
    <!-- ko template: getTemplate() --><!-- /ko -->
    <script type="text/x-magento-init">
        {
            "#checkout": {
                "Magento_Ui/js/core/app": <?= /* @noEscape */ $block->getJsLayout() ?>
            }
        }
    </script>
    <script>
        window.checkoutConfig = <?= /* @noEscape */ $block->getSerializedCheckoutConfig() ?>;
        // Create aliases for customer.js model from customer module
        window.isCustomerLoggedIn = window.checkoutConfig.isCustomerLoggedIn;
        window.customerData = window.checkoutConfig.customerData;
    </script>
    <script>
        require([
            'mage/url',
            'Magento_Ui/js/block-loader'
        ], function(url, blockLoader) {
            blockLoader("<?= $block->escapeJs($block->escapeUrl($block->getViewFileUrl('images/loader-1.gif'))) ?>");
            return url.setBaseUrl('<?= $block->escapeJs($block->escapeUrl($block->getBaseUrl())) ?>');
        })
    </script>
</div>
<script type="text/javascript">
require(['jquery'], function($){

	$(window).bind("load", function() { 
		 $(this).scrollTop(0); 
	});
    
    
});
</script>
<script type="text/javascript">
    require([ 'jquery', 'jquery/ui'], function($){
    	$(document).ajaxComplete(function () {
    	 $(".select option[value='533'],.select option[value='534'],.select option[value='535'],.select option[value='536'],.select option[value='537'],.select option[value='538'],.select option[value='539'],.select option[value='540'],.select option[value='541'],.select option[value='543'],.select option[value='544'],.select option[value='546'],.select option[value='547'],.select option[value='548'],.select option[value='550'],.select option[value='551'],.select option[value='552'],.select option[value='554'],.select option[value='555'],.select option[value='556'],.select option[value='557'],.select option[value='558'],.select option[value='559'],.select option[value='609'],.select option[value='610'],.select option[value='560'],.select option[value='561'],.select option[value='562'],.select option[value='565'],.select option[value='567'],.select option[value='568']").remove();
           });
    	
   /*     $(document).on('click', "input[type='radio']", function () {
        var checkpaymentmode = $(this).val();
        if(checkpaymentmode == 'razorpay'){
        $('.primary.razorpay').find('.action.primary.checkout').trigger('click');
         }
        else if(checkpaymentmode == 'cashondelivery'){
          var i = 0;
          timer = setInterval(function() {
           i++;
           if(i>=50){
          $('.primary.cod').find('.action.primary.checkout').trigger('click');
           clearInterval(timer);
          }
         }, 1);
         }
        });*/

        $(document).on("click",".opc-continue-click", function() {
           
           $(".opc-block-shipping-information").hide();
        });

        $(document).on("click","#shipping-view , #shipping-view-mobile, .fa fa-arrow-left", function() {
           
            $(".opc-block-shipping-information").show();
        });

/*************************************/

function stateSelect(cityId){
	
if(cityId==''){	
		  var cityId = $.cookie('selected_city');
	}
if(cityId==''){	
		  var cityId = $('.product_cities_select').val();
	}

//alert('s '+cityId);
			if((cityId == 4) || (cityId == 5)){
				$('select[name="region_id"]').find('option[value="566"]').attr('selected','selected');
				$('select[name="region_id"]').val(566).change();
			}
			else if(cityId == 1){
				$('select[name="region_id"]').find('option[value="542"]').attr('selected','selected');
				$('select[name="region_id"]').val(542).change();
			}
			else if((cityId == 3) || (cityId == 2) ){
				$('select[name="region_id"]').find('option[value="545"]').attr('selected','selected');
				$('select[name="region_id"]').val(545).change();
			}
			else if((cityId == 8) || (cityId == 9) ){
				$('select[name="region_id"]').find('option[value="564"]').attr('selected','selected');
				$('select[name="region_id"]').val(564).change();
			}
			else if(cityId == 10 ){
				$('select[name="region_id"]').find('option[value="549"]').attr('selected','selected');
				$('select[name="region_id"]').val(549).change();
			}
			else if((cityId == 6) || (cityId == 7) || (cityId == 11) || (cityId == 12) || (cityId == 13) || (cityId == 14)){
				$('select[name="region_id"]').find('option[value="553"]').attr('selected','selected');
				$('select[name="region_id"]').val('553').change();
			}
			else if(cityId == 16){
				$('select[name="region_id"]').find('option[value="563"]').attr('selected','selected');
				$('select[name="region_id"]').val(563).change();
			}

}
	
function citySelect(cityId){
	if(cityId==''){	
		  var cityId = $.cookie('selected_city');
	}
	if(cityId==''){	
	  var cityId = $('.product_cities_select').val();
	}

//alert('c '+cityId);
	$('select[name="custom_attributes[custom_city]"]').find('option[value="'+cityId+'"]').attr('selected', 'selected');
}

//$(document).ajaxStop(function () {
	$(window).load(function() {
//alert('onload');		
setTimeout(function(){
			// var cityval = $('.product_cities_select').val();
			var cityval = $.cookie('selected_city');	
			citySelect(cityval);
			stateSelect(cityval);
		}, 2000);
	
	});
//});		
		
$(document).on('change', "[name='custom_attributes[custom_city]']", function () {
		var cityId = $('select[name="custom_attributes[custom_city]"]').val();
		stateSelect(cityId);					
});
	

$(document).on('change', '.product_cities_select', function () {
		var cityId = $(this).val();
		stateSelect(cityId);				
});

/**************************************/
    });
</script>

<script type="text/javascript">
require(['jquery'], function($){
    $( document ).ready(function() {
        $(document).on('change', '#customer-email', function () {
            var email = $("#customer-email").val();
            var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            if(!regex.test(email)) {
                $(this).parent().addClass('form-cross');
                $(this).parent().removeClass('form-tick');

            }else{
                $(this).parent().addClass('form-tick');
                $(this).parent().removeClass('form-cross');
            } 
        });

        
        $(document).on('change', 'input[name="full_name"], input[name="street[0]"]', function () {
            var fullName = $(this).val();
            if(fullName.length > 0){
                $(this).parent().addClass('form-tick');
                $(this).parent().removeClass('form-cross');
            }else{
                $(this).parent().addClass('form-cross');
                $(this).parent().removeClass('form-tick');
            }
        });

        $(document).on('change', 'input[name="telephone"]', function () {
            var mobValue = $(this).val();
            var phoneno = /^[1-9]\d{9}$/;
            if(mobValue.match(phoneno)){
                $(this).parent().addClass('form-tick');
                $(this).parent().removeClass('form-cross');
                //return true;
            }else{
                $(this).parent().addClass('form-cross');
                $(this).parent().removeClass('form-tick');
                //return false;
            }
        });


        $(document).on('keyup', 'input[name="telephone"]', function () {
            var mobValue = $(this).val();
            var firstDigitStr = String(mobValue)[0];
            nubval = parseInt(firstDigitStr);
            var curerrmsg = '';
            if(mobValue.length<10){
                var curerrmsg = '<span data-bind="text: element.error">Please enter more or equal than 10 symbols.</span>';
            }else{
                var curerrmsg = '<span data-bind="text: element.error">Please enter less or equal than 10 symbols.</span>';
            }
            if(nubval<1){
                $('.field-error').html('<span data-bind="text: element.error">Please enter valid mobile number</span>');
                $(this).focus();
                $(this).val('');
            }else{
                $('.field-error').html(curerrmsg);		
            }

        });






        $(document).on('change', 'input[name="postcode"]', function () {
            var zipcodeValue = $(this).val();
            var evalidate = /^\d{6}(-\d{5})?$/;
           if (zipcodeValue.match(evalidate)){
                $(this).parent().addClass('form-tick');
                $(this).parent().removeClass('form-cross');
            }else{
                $(this).parent().addClass('form-cross');
                $(this).parent().removeClass('form-tick');
            }
        });


        $(document).on('click', '.opc-continue-click', function () {
            console.log('Submit');
            var email = $("#customer-email").val();
            var regex = /^([a-zA-Z0-9_\.\-\+])+\@(([a-zA-Z0-9\-])+\.)+([a-zA-Z0-9]{2,4})+$/;
            if(!regex.test(email)) {
                $("#customer-email").parent().addClass('form-cross');
                $("#customer-email").parent().removeClass('form-tick');

            }else{
                $("#customer-email").parent().addClass('form-tick');
                $("#customer-email").parent().removeClass('form-cross');
            } 

            var fullName = $('input[name="full_name"]').val();
            if(fullName.length > 0){
                $('input[name="full_name"]').parent().addClass('form-tick');
                $('input[name="full_name"]').parent().removeClass('form-cross');
            }else{
                $('input[name="full_name"]').parent().addClass('form-cross');
                $('input[name="full_name"]').parent().removeClass('form-tick');
            }

            var addressVal = $('input[name="street[0]"]').val();
            if(addressVal.length > 0){
                $('input[name="street[0]"]').parent().addClass('form-tick');
                $('input[name="street[0]"]').parent().removeClass('form-cross');
            }else{
                $('input[name="street[0]"]').parent().addClass('form-cross');
                $('input[name="street[0]"]').parent().removeClass('form-tick');
            }

            var mobValue = $('input[name="telephone"]').val();
            var phoneno = /^\d{10}$/;
            if(mobValue.match(phoneno)){
                $('input[name="telephone"]').parent().addClass('form-tick');
                $('input[name="telephone"]').parent().removeClass('form-cross');
                //return true;
            }else{
                $('input[name="telephone"]').parent().addClass('form-cross');
                $('input[name="telephone"]').parent().removeClass('form-tick');
                //return false;
            }

            var zipcodeValue = $('input[name="postcode"]').val();
            var evalidate = /^\d{6}(-\d{5})?$/;
           if (zipcodeValue.match(evalidate)){
                $('input[name="postcode"]').parent().addClass('form-tick');
                $('input[name="postcode"]').parent().removeClass('form-cross');
            }else{
                $('input[name="postcode"]').parent().addClass('form-cross');
                $('input[name="postcode"]').parent().removeClass('form-tick');
            }  

        })
    })
});
    
</script>