<script>

require(["jquery"], function($) {
var sa = document.createElement("script");
sa.async = "true"
sa.src = "https://www.googletagmanager.com/gtag/js?id=AW-633120097";

$("head").append(sa);



var scri = document.createElement("script");
scri.innerHTML = "window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'AW-633120097'); ";


$("head").append(scri);

});

</script>
