<?php

$objectManager = \Magento\Framework\App\ObjectManager::getInstance();

$blockObj = $objectManager->get('\Ves\Brand\Model\Brand');

$_brandCollection = $blockObj->getCollection()
->setOrder('position','ASC')           
->addFieldToFilter('status',1)
->addFieldToFilter('group_id',2);

//$blockObj= $this->getLayout()->createBlock('\Ves\Brand\Block\Brandlist');

//$_brandCollection = $this->getBrandCollection();
//$show_brand_name = $this->getConfig('brand_list_page/show_brand_name');
//echo $_brandCollection->getSelect()->__toString();


$mediaUrl =  $this->getUrl('pub/media');
if(count($_brandCollection) > 0):
	
  ?>
          <?php $c = 0; foreach($_brandCollection as $key => $_brand):

         // print_r($_brand->getData());

           if ($c == 8) { break; }  ?>
        <div class="col-md-3">
					<div class="br_col4_inner">
						<a href="<?php echo $_brand->getUrl(); ?>">
							<img alt="<?php echo  $_brand->getName();?>" class="img-responsive tnm-logo-adjust" src="<?php echo $_brand->getThumbnailUrl(); ?>">
						  </a>
					</div>
				</div>
          <?php $c++; endforeach; ?>
<?php endif; ?>

