<?php /*Car and Bike Section start*/ ?>
<?php
$data = file_get_contents(BP.'/api/battery.json');
$bikeBatteryId = 4242;
// if (isset($_SERVER['HTTP_HOST']) && strpos($_SERVER['HTTP_HOST'], 'staging') === false) {
     $bikeBatteryId = 4152;
// }
?>
<script>
var bikeBatteryId = '<?= $bikeBatteryId; ?>';
var api_data = <?php echo $data; ?>;
require(["jquery", "js/select2"], function($) {

    // function for support ie and safari
    if (!Array.prototype.find) {
        Object.defineProperty(Array.prototype, 'find', {
            value: function (predicate) {
            // 1. Let O be ? ToObject(this value).
            if (this == null) {
                throw new TypeError('"this" is null or not defined');
            }
        
            var o = Object(this);
        
            // 2. Let len be ? ToLength(? Get(O, "length")).
            var len = o.length >>> 0;
        
            // 3. If IsCallable(predicate) is false, throw a TypeError exception.
            if (typeof predicate !== 'function') {
                throw new TypeError('predicate must be a function');
            }
        
            // 4. If thisArg was supplied, let T be thisArg; else let T be undefined.
            var thisArg = arguments[1];
        
            // 5. Let k be 0.
            var k = 0;
        
            // 6. Repeat, while k < len
            while (k < len) {
                // a. Let Pk be ! ToString(k).
                // b. Let kValue be ? Get(O, Pk).
                // c. Let testResult be ToBoolean(? Call(predicate, T, « kValue, k, O »)).
                // d. If testResult is true, return kValue.
                var kValue = o[k];
                if (predicate.call(thisArg, kValue, k, o)) {
                return kValue;
                }
                // e. Increase k by 1.
                k++;
            }
        
            // 7. Return undefined.
            return undefined;
            }
        });
    }

    var local = false;
    var availableModes = {
        brand: "brand",
        size: "size"
    };
    var searchMode;
    var brandOrWidthSelector, modelOrProfileSelector, variantOrRimSelector;
    var currentToggleState, _selected, _id, _level, _globalResponse;
    var getData = function() {};
    var CACHE = {};

    function __ddmap(o) {
        var obj = {
            id: o.entity_id,
            text: o.name
        };
        return obj;
    }

    function __find(id) {
        return function(o) {
            return o.entity_id == id;
        };
    }

    function __formatForSize(level, path, entities) {
        return function(obj) {
            var id = obj[entities[level]];
            var nextPath = path + "/" + id;
            // Get non numerical keys
            var children = Object.keys(obj)
                .filter(function(k) {
                    return !isNaN(parseInt(k));
                })
                .map(function(k) {
                    return obj[k];
                });
            return {
                entity_id: id,
                name: obj.label,
                path: nextPath,
                is_active: "1",
                is_anchor: obj.url ? "1" : "0",
                request_path: obj.url || null,
                childes: children.map(__formatForSize(level + 1, nextPath, entities))
            };
        };
    }

    function formatData(data) {
        if (searchMode === availableModes.brand) {
            return data;
        } else if (searchMode === availableModes.size) {
            var path = "1/375/3404/" + currentToggleState.toString();
            var ientity = currentToggleState == 42 ? "bikeid" : "carid";
            var name = currentToggleState == 42 ? "Bike Search" : "Car Search";
            var wrapper = [{
                entity_id: currentToggleState.toString(),
                name: name,
                path: path,
                is_active: "1",
                is_anchor: "1",
                request_path: "",
                childes: data.map(
                    __formatForSize(0, path, [ientity, "profileid", "rimid"])
                )
            }];
            return wrapper;
        }
    }

    function _init(response) {
        if (typeof response === "string") {
            response = formatData(JSON.parse(response));
            console.log(response);
        }
        _globalResponse = response;
        _level = 0;
        refresh();
    }

    function fromSelected(level) {
        var ps = _selected.path.split("/");
        ps.shift();
        ps.shift();
        ps.shift();
	ps.shift();
        var e = _globalResponse.find(__find(currentToggleState));
        for (var i = 0; i < level; i++) {
            e = e.childes.find(__find(ps[i]));
        }
        return e;
    }

    function switchMode(el) {
        var placeholder = "";
        var mode = el.data("selector");
        switch (mode) {
            case "brand width":
                if (searchMode === availableModes.brand) {
                    placeholder = "Select Brand";
                } else if (searchMode === availableModes.size) {
                    placeholder = "Select Width";
                }
                break;
            case "model profile":
                if (searchMode === availableModes.brand) {
                    placeholder = "Select Model";
                } else if (searchMode === availableModes.size) {
                    placeholder = "Select Profile";
                }
                break;
            case "variant rim":
                if (searchMode === availableModes.brand) {
                    placeholder = "Select Variant";
                } else if (searchMode === availableModes.size) {
                    placeholder = "Select Rim";
                }
                break;
        }
        $('[data-label="' + mode + '"]').html(placeholder);
        el.html("").select2({
            placeholder: placeholder,
            //sortResults: data => data.sort((a, b) => a.text.localeCompare(b.text)),
            sortResults: function(data) { 
                data.sort(function(a, b) { return a.text.localeCompare(b.text)})
            },
            minimumResultsForSearch: -1
        });
        return placeholder;
    }

    function initSelect(el) {
        var placeholder = switchMode(el);
        return function(_e) {
            var entry = _e.childes.map(__ddmap);
            entry.unshift({
                id: "",
                text: ""
            });
            el.html("").select2({
                //data: entry.sort((a, b) => a.text.localeCompare(b.text)),
                data: entry.sort(function(a, b) { return a.text.localeCompare(b.text)}),
                placeholder: placeholder,
                minimumResultsForSearch: -1
            });
            // Trigger Change Event
            el.trigger("change");
        };
    }

    function refresh() {
        _selected = _globalResponse.find(__find(currentToggleState));
        if (_selected !== undefined) {
            initSelect(brandOrWidthSelector)(_selected);
            initSelect(modelOrProfileSelector);
            initSelect(variantOrRimSelector);
            _level = 0;
        }
    }

    function submitSearch(e) {
        console.log("submitSearch", e);
        try {
            e.preventDefault();
            e.stopPropagation();
        } catch (err) {
            console.error(err);
        }
        var next = undefined;
        //if (_id !== null) {
        //    next = _selected.childes.find(__find(_id));
        //} else {
            next = _selected;
        //}
        if (next) {
            window.location.href = next.request_path;
        }
    }

    function toggleState(e) {
        console.log("toggleState", e);
        try {
            e.preventDefault();
            e.stopPropagation();
        } catch (err) {
            console.error(err);
        }
        currentToggleState = $(this).data("state");
        $("[data-state-toggle]").removeClass("active");
        $(this).addClass("active");
        // if (searchMode === availableModes.brand) {
        //     refresh();
        // } else {
        //     getData().then(_init);
        // }
        getData().then(_init);
    }

    function updateSelector(level, nselector) {
        return function(e) {
            try {
                e.preventDefault();
                e.stopPropagation();
            } catch(err) {}
            console.log(_selected);
            var current = $(this).val();
            if (current === "") {
                if (nselector !== null && nselector !== undefined) {
                    switchMode(nselector);
                }
                return;
            }
            var next;
            if (level == _level) {
                next = _selected;
            } else {
                next = fromSelected(level);
            }
            next = next.childes.find(__find(current));
            if (next !== undefined) {
                _id = next.childes.length > 0 ? current : null;
                _selected = next;
                _level++;
                if (nselector !== null) {
                    initSelect(nselector)(next);
                    console.log(next);
                }
            } else {
                console.log("Something's amiss");
            }
        };
    }

    function toggleSearchMode(e) {
        console.log("toggleSearchMode", e);
        try {
            e.preventDefault();
            e.stopPropagation();
        } catch (err) {
            console.error(err);
        }
        searchMode = $(this).data("mode");
        $("[data-mode-toggle]").removeClass("active");
        $(this).addClass("active");
        getData().then(_init);
    }

    function getPath() {
        console.log(currentToggleState);
        if (currentToggleState === 3405) {
            return "Carsearch";
        } else {
            return "Bikebatterysearch";
        }
    }

    function _cachedGetData() {
        // Setup Initial Cache
        CACHE = {};
        return function() {
            $("#overlay").fadeOut();
            //return new Promise(function(resolve, reject) {
                var promise = $.Deferred();
                var url;
                var urlPrefix = window.location.origin;
                if (local) {
                    urlPrefix = "https://tyress.clarksfield.com";
                }
                if (searchMode === availableModes.brand) {
                    url = urlPrefix + "/api/battery.json";
                    if(currentToggleState == bikeBatteryId) {
                        url = urlPrefix + "/tyreadvanceserch/index/" + getPath();
                    }
                } else if (searchMode === availableModes.size) {
                    url = urlPrefix + "/tyreadvanceserch/index/" + getPath();
                } else {
                    promise.reject(new Error("No Mode Available for " + searchMode));
                }
                // Check if CACHED data exists
                if (CACHE[url] !== undefined) {
                    promise.resolve(CACHE[url]);
                } else {
                    // CACHE[url] = api_data;
                    // promise.resolve(api_data);
                    
                    // $("#overlay").fadeIn();
		            console.log('SENDING: ', url);
                    $.get(url)
                        .then(function(response) {
		                    // Store in Cache
			                console.log('RESPONSE:', response);
                            CACHE[url] = response;
                            // $("#overlay").fadeOut();
                            promise.resolve(response);
                        }, function(err) {
                            // $("#overlay").fadeOut();
                            console.error(err);
                            promise.reject(err);
                        });
                    
                }
                return promise;
            //});
        };
    }

    getData = _cachedGetData();

    // Script Entry Point
    // Dropdowns with Select2
    $("[data-selector]").select2();
    brandOrWidthSelector = $('[data-selector="brand width"]').first();
    modelOrProfileSelector = $('[data-selector="model profile"]').first();
    variantOrRimSelector = $('[data-selector="variant rim"]').first();
    // Add Event Listener on Dropdowns
    brandOrWidthSelector.on("change", updateSelector(0, modelOrProfileSelector));
    modelOrProfileSelector.on("change", updateSelector(1, variantOrRimSelector));
    variantOrRimSelector.on("change", updateSelector(2, null));
    // Toggle Event Listeners
    $("[data-mode-toggle]").on("click", toggleSearchMode);
    $("[data-search-toggle]").on("click", toggleState);
    // Configure Search Button
    $("[data-search-init]").on("click", submitSearch);
    // Set search Mode
    searchMode = $("[data-mode-toggle].active")
        .first()
        .data("mode");
    // Set current State
    currentToggleState = $("[data-search-toggle].active")
        .first()
        .data("state");
    getData().then(_init);
});
</script>

<!-- carousel start -->
<style>
.owl-stage-outer {
    width: 100%;
}
@media (max-width: 767px) {
    .mob-nopad {
        float:none !important;
    }
}
</style>
<div class="car_bike_section" style="position:relative">
    <div class="battery-page-slider hidden-xs hidden-sm">
			<?= $block->getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget')->setSliderId(3)->toHtml();?>
	</div>
	<div class="battery-page-form">
        <div class="">
            <div class="row">   
                <div class="col-md-12 mob-nopad">
                    <div id="overlay" style="display:none;">
                        <div class="spinner"></div>
                        <br/>
                    </div>
                    <div class="find_tyre_sec2">
                        <div class="tyre_title" style=" background: #f2f2f2; text-align: center;padding:5px; ">
                            <h1 class="form-heading-h2" style="font-size:18px;padding: 0px;">Get Battery Fitted at Your Home</h1>
                            <p  style="font-size: 13px;padding: 0px;margin:0px;">In Bengaluru, Chennai, Delhi NCR, Hyderabad, Mumbai & Pune</p>
                        </div>
                        <div class="row">
                            <div class="col-xs-12 hidden">
                                <div class="row brd_vichle_1">
                                    <p>Search By</p>
                                    <div class="col-xs-6">
                                    <button data-mode-toggle data-mode="brand" class="vech_btn_1 active">Vehicle Brands</button>
                                    </div>
                                    <div class="col-xs-6">
                                    <button data-mode-toggle data-mode="size" class="vech_btn_1">Tyres Size</button>
                                    </div>
                                </div>
                            </div> 
                            <div class="col-xs-12">
                                <div class="brd_vichle_1 tt1 row">
                                    <div class="btn_second col-xs-6">
                                    <button data-search-toggle data-state="3405" id="bike46" class="vech_btn_2 active tt"><h2>Car battery</h2></button>
                                    </div>
                                    <div class="btn_first col-xs-6">
                                    <button data-search-toggle data-state="<?= $bikeBatteryId; ?>" id="bike42" class="vech_btn_1 tt"><h2>2 Wheeler battery</h2></button>
                                    </div>
                
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-12 col-md-6 col-xs-6 col-sm-6">
                                <div class="select_brand_sec">
                                    <label data-label="brand width">Select Brand </label>
                                    <select data-selector="brand width"></select>
                                </div>
                            </div>
                            <div class="col-lg-12  col-md-6 col-xs-6 col-sm-6">
                                <div class="select_brand_sec">
                                    <label data-label="model profile">Select Model</label>
                                    <select data-selector="model profile"></select>
                                </div>
                            </div>
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="select_brand_sec">
                                    <label data-label="variant rim">Select Fuel Type</label>
                                    <select data-selector="variant rim"></select>
                                </div>
                            </div>
                            <div class="col-md-12 col-xs-12 col-sm-12">
                                <div class="find_tyre_btn" data-search-init>
                                    <a data-search-init href="#"><h3>Find Battery</h3></a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="home-page-slider hidden-lg hidden-md ">
        <?= $block->getLayout()->createBlock('Mageplaza\BannerSlider\Block\Widget')->setSliderId(4)->toHtml();?>
    </div>
</div>

<?php /* ?>
<div class="car_bike_section" style="background:linear-gradient(rgba(0,0,0,.7),rgba(0,0,0,.29)),url(/media/wysiwyg/23d38c50-b615-403f-9882-d29f788714ac.jpg) no-repeat 0 50%; background-size: cover;">
    <div class="container">
      <div class="section_second">
      <div class="row">   
          <div class="col-md-5 pull-right mob-nopad">
<div id="overlay" style="display:none;">
    <div class="spinner"></div>
    <br/>
</div>
            <div class="find_tyre_sec2">
              <div class="tyre_title" style=" background: #f2f2f2; text-align: center;padding-top:0px; ">
             <!--   <p class="form-heading-h2">Tyres fitted at your doorstep</p> -->
		 <p class="form-heading-h2" style="font-size:18px;padding: 0px;">Get Battery Fitted at Your Home</p>
                <p  style="font-size: 13px;padding: 0px;">In Hyderabad, Bengaluru, Mumbai, Pune & Delhi NCR</p>
              </div>
<!--          <p style="text-align: center;font-size: 13px;border-bottom: 1px solid #f3f3f3;
      padding: .6rem 0;">We Also Provide Home Delivery of Batteries in All Other Major cities of india.
      </p> -->
              <div class="row">
                <div class="col-xs-12 hidden">
                  <div class="row brd_vichle_1">
                    <p>Search By</p>
                    <div class="col-xs-6">
                      <button data-mode-toggle data-mode="brand" class="vech_btn_1 active">Vehicle Brands</button>
                    </div>
                    <div class="col-xs-6">
                      <button data-mode-toggle data-mode="size" class="vech_btn_1">Tyres Size</button>
                    </div>
                  </div>
                </div> 
                <div class="col-xs-12 hidden">
                  <div class="brd_vichle_1 tt1 row">
                    <p>Batteries for?</p>
                    <div class="btn_second col-xs-6">
                      <button data-search-toggle data-state="3405" id="bike46" class="vech_btn_2 active tt">Car</button>
                    </div>
                    <div class="btn_first col-xs-6">
                      <button data-search-toggle data-state="42" id="bike42" class="vech_btn_1 tt">Bike</button>
                    </div>
  
                  </div>
                </div>
              </div>
              <div class="col-md-12">
              <div class="select_brand_sec">
                  <label data-label="brand width">Select Brand </label>
                  <select data-selector="brand width"></select>
                </div>
              </div>
              <div class="col-md-12">
                <div class="select_brand_sec">
                  <label data-label="model profile">Select Model</label>
                  <select data-selector="model profile"></select>
                </div>
              </div>
              <div class="col-md-12">
                <div class="select_brand_sec">
                  <label data-label="variant rim">Select Fuel Type</label>
                  <select data-selector="variant rim"></select>
                </div>
              </div>
              <div class="col-md-12">
                <div class="find_tyre_btn" data-search-init>
                  <a data-search-init href="#">Find Batteries</a>
                </div>
              </div>
               <div class="col-md-12">
                <div class="expert_sec">
             <!--     <i class="fa fa-volume-control-phone expert" aria-hidden="true"></i> <a href="#">Talk to our tyres expert</a> -->
                </div>
              </div>
            </div>


<div class="car_sec1" style=" padding-top: 0px; ">
<div class="text_sec1">
<h1><span class="text_color" style="font-size: 20px !important;">Buy car Battery online | Buy Bike Battery Online<br></span></h1>
<h2 style="font-size: 20px; color: #fcc624;"> Get Batteries changed at your doorstep </h2> <!-- <a href=" https://tyres.clarksfield.com/checkout/#shipping"> <h1><span class="text_color">Buy Car &amp; Bike</span> Tyres Online.</h1>
<h4 style="font-size: 24px; color: #d31e23;">Tyres fitted at your doorstep*</h4> </a>-->
<!--<p class="banner-subheading">What you get :</p>-->
</div>
<div class="inner_text_sec">
<h6 style="font-size: 18px;font-weight: 500;color: #fff;padding-top: 10px;" >Best Battery Prices | Bike Battery | Scooter battery Price |Car battery price | Battery shop near me | Buy Battery Online | Exide battery price | Amaron Battery Price </h6>
<!--<ul>
<li style="margin: unset;">
<h2 class="tick">Best Tyre Prices | All Tyre Sizes available</h2>
</li>
<li style="margin: unset;">
<h6 class="tick">Online Tyre Purchase made easy</h6>
</li>
<li style="display: none; margin: unset; list-style-type: '✓   ';">
<h4>Hot deals and discounts on tyres</h4>
</li>
<li style="display: none; margin: unset; list-style-type: '✓   ';">
<h5>Convenience of tyres fitted at home or office</h5>
</li>
</ul> -->
</div>
</div>
          </div>
          <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('buycarbike-battery')
                                ->toHtml();
                                ?>
      </div>
      </div>
    </div>
</div>
<?php */ ?>
   <!-- ==================Car and Bike Section end================== -->
   <div class="hw_section">
      <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('how_it_works_battery')
                                ->toHtml();
                                ?>


  </div>  
   <div class="hw_section">
      <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('what-you-get-battery')
                                ->toHtml();
                                ?>
     </div>
  
  <!-- =================How it work section start==================== -->
       </div> 
  <!-- =====================How it work section end ===================== -->
  
  <!-- =================Tyres brand section satrt================== -->
  <div class="tyrsbrand_section">
      <div class="container">
          <div class="row">
                <div class="col-md-12">
                    <div class="hw_tittle">
                        <p class="h1"><span class="text_color">Batteries</span> By Brands</p>
                    </div>
                    
                    <div class="title_img"><img loading="lazy" src="<?php echo $this->getViewFileUrl('images/line.png'); ?>" alt="section-start" ></div>
                </div>
                <ul class="tabs">
                    <li class="car_bt"><a class="tab active" rel="#tabcontent1">Car Brands</a></li>
                    <li class="bikes_bt"><a class="tab" rel="#tabcontent2">Bikes Brands</a></li>
                </ul>
                <div class="tab_content_container">
                    <div id="tabcontent1" class="tab_content tab_content_active">
                    <!--car phtml-->
                        <div class="brd_col4 bbb_l_r owl-carousel col-md-12" id="owl-carousel-car-battery">
                        <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/cars-battery.phtml")->toHtml();?>
                        </div>
                    <!-- close section -->
                    </div>
                    <div id="tabcontent2" class="tab-wrapper tab_content">
                        <div class="brd_col4 bbb_l_r_1 owl-carousel col-md-12"  id="owl-carousel-bike-battery">
                        <?php  echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/bikes-battery.phtml")->toHtml();?>
                        <!-- close section -->
                        </div>
                    </div>
                </div>
              </div>
              </div>
              </div>
  
  <!-- ================Tyres brand section end======================== -->
   <div class="tyrswiderange_section">
      <div class="container">
          <div class="row">
              <div class="col-md-12">
                  <div class="hw_tittle">
                      <p class="h1"><span class="text_color">Our Wide Range</span> Of Battery Brands</p>
                  </div>
                  <div class="title_img">
                      <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/line.png'); ?>" alt="section-start">
                  </div>
              </div>
        <div class="wide-range-tyres-battery owl-carousel col-md-12" id="owl-carousel-battery-wide-range">
             <?php echo $this->getLayout()->createBlock("Magento\Framework\View\Element\Template")->setTemplate("Magento_Theme::html/battery-brand.phtml")->toHtml();?>
        </div>
          </div>
      </div>
  </div>
 
  <!-- ========================Top Selling Tyres======================= -->
  <div class="container-fluid">
      <div class="top-selling" style="background-color: #fff;">
          <div class="container">
           <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('top_seller-battery')
                                ->toHtml();
                                ?>
  
          </div>
      </div>
  </div>
  <!-- ===================top selling tyres end================ -->
  
  <!-- ======================Batteries==================== -->
  
  <!-- ======================Try Our Tyer Decision Guide start==================== -->
  
  
  <!-- ===================Try Our Tyer Decision Guide end====================== -->
  <!-- ===========================what our custmer speek====================== -->
  <div class="container-fluid">
    <div class="sustom_spk_sec">
    <div class="container">
      <div class="cust_speak">
        <div class="hw_tittle cust_spek_title">
          <p class="h1"><span>Customers</span> Speak</p>
        </div>
        <div class="image_title_botom">
          <img loading="lazy" src="<?php echo $this->getViewFileUrl('images/line.png'); ?>" alt="section-start">
        </div>
      <!-- <?php //echo $this->getLayout()->createBlock("Clarksfield\Customersspeak\Block\CustomersspeakListData")->setTemplate("Magento_Theme::html/video/list.phtml")->toHtml();?> -->
      </div>
      <div class="cust_speak_bottom">
        <?php //echo $this->getLayout()->createBlock("Tyresclarksfield\Testimonials\Block\TestimonialsListData")->setTemplate("Magento_Theme::html/testimonials/list.phtml")->toHtml();?>
        <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('battery-testimonial')
                                ->toHtml();
                                ?>
      </div>
  
    </div>
  </div>
  </div>
  <!-- ======================page bottom======================= -->
  <div class="container-fluid">
     <div class="page-bottom">
        <div class="container">
           <div class="row">
               <div class="col-md-12">
                 <h2 class="title section-title zero-contact-fitment">Zero-Contact Battery Fitment Service</h2>
                 <div class="">
 <?php echo $this->getLayout()
                                ->createBlock('Magento\Cms\Block\Block')
                                ->setBlockId('Zero-Contact-battery')
                                ->toHtml();
                                ?>
                 </div>
              </div>
              <div class="col-md-12">
                 <h2 class="title section-title faq">Frequently Asked Questions</h2>
                 <div class="accordion">
                    
                      <?php
                       echo $this->getLayout()->createBlock("Tyres\Faq\Block\FaqListData")->setTemplate("Magento_Theme::html/Faq/battery-list.phtml")->toHtml();
                       ?>
                       
                    </div>
                 </div>
            <!--  <div class="col-md-6">
                 <p class="page-bottom_title main-heading h4">Our Blog</p>
                 <div class="blog-section">
                     <?php //echo $this->getLayout()->createBlock("Mageplaza\Blog\Block\Post\Listpost")->setTemplate("Magento_Theme::html/post/list.phtml")->toHtml();?>
                 </div>
              </div> 
           </div>
        </div>
     </div>
  </div> -->
           </div>
        </div>
     </div>
  </div>
</div>
  <!-- mobile design brand -->
<div class="brand_section_last">
    <div class="container">
      <div class="row">
       <div class="col-md-12">
<div class="brand_last_inner mob_text_3">
  <div class="accordion-item">
  <div class="accordion-item-header">
<p class="footer-seo-title h3">You can buy tyres online for the following  brand </p>
</div>
<div class="accordion-item-body">
                        <div class="accordion-item-body-content">
<ul>
 <?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = 376; //Parent Category ID
$subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subCats = $subCategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
foreach ($subCats as $subcat) {
  ?><?php
$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
$subcaturl = $subcat->getUrl();
?>
<li><a href="<?php echo $subcaturl ;?>" title="<?php echo $subcat->getName(); ?>"><?php echo $subcat->getName(); ?></a></li>

<?php }?>
</ul>
</div>
</div>
</div>
<div class="brand_last_inner mob_text_3">
<div class="accordion-item">
<div class="accordion-item-header">
<p class="footer-seo-title h3">Check tyre prices and tyre size for your car from the list below </p>
</div>
<div class="accordion-item-body">
                        <div class="accordion-item-body-content">
<ul>
 <?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = 46; //Parent Category ID
$subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subCats = $subCategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
foreach ($subCats as $subcat) {
  ?><?php
$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
$subcaturl = $subcat->getUrl();
?>
<li><a href="<?php echo $subcaturl ;?>" title="<?php echo $subcat->getName(); ?>"><?php echo $subcat->getName(); ?></a></li>

<?php }?>
</ul>
</div>
</div>
</div>
</div>
<div class="brand_last_inner mob_text_3">
  <div class="accordion-item">
                     <div class="accordion-item-header">
<p class="footer-seo-title h3">Check tyre prices and tyre size for your bike from the list below </p>
</div>
 <div class="accordion-item-body">
                        <div class="accordion-item-body-content">
<ul>
 <?php  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$catId = 42; //Parent Category ID
$subCategory = $objectManager->create('Magento\Catalog\Model\Category')->load($catId);
$subCats = $subCategory->getChildrenCategories();
$_helper = $this->helper('Magento\Catalog\Helper\Output');
?>
<?php
foreach ($subCats as $subcat) {
  ?><?php
$_category = $objectManager->create('Magento\Catalog\Model\Category')->load($subcat->getId());
$subcaturl = $subcat->getUrl();
?>
<li><a href="<?php echo $subcaturl ;?>" title="<?php echo $subcat->getName(); ?>"><?php echo $subcat->getName(); ?></a></li>

<?php }?>
</ul>
</div>
</div>
</div>
</div>
        
      </div>
    </div>  
  </div>
</div>
</div>
<!-- close desighn -->
  <?php
	$objectManager = \Magento\Framework\App\ObjectManager::getInstance();
	$storeManager = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
	$baseurl=$storeManager->getStore()->getBaseUrl(\Magento\Framework\UrlInterface::URL_TYPE_LINK);
	   ?>
   <input type="hidden" value="<?php echo $baseurl; ?>" id="baseUrl"/> 
  <!-- ================== Shop By Brand Section start ============== -->
  
  
  <!-- ================== Shop By Brand Section end ============== -->
 <script>
  require(["jquery"],function($){
  $(document).ready(function(){
      $(".tabs li a").click(function() {
  
          // Active state for tabs
          $(".tabs li a").removeClass("active");
          $(this).addClass("active");
  
          // Active state for Tabs Content
          $(".tab_content_container > .tab_content_active").removeClass("tab_content_active").fadeOut(200);
          $(this.rel).fadeIn(500).addClass("tab_content_active");
      });
  });
  $(document).ready(function() {
  $("#bike42").click(function () {
      $("#bike46").removeClass("active");
      // $(".tab").addClass("active"); // instead of this do the below
      $("#bike42").addClass("active");
    });
  $("#bike46").click(function () {
      $("#bike42").removeClass("active");
      // $(".tab").addClass("active"); // instead of this do the below
      $("#bike46").addClass("active");
    });
  
  });
  });
     
     requirejs(['jquery','owlcarousel'], function(jQuery, owl){
        jQuery(function($) {
              var owl = $('#owl-carousel-car-battery, #owl-carousel-bike-battery, #owl-carousel-battery-wide-range');
                owl.owlCarousel({
                    margin: 10,
                    lazyLoad:true,
                    loop: false,
                    autoWidth: false,
                    responsiveClass:true,
                    responsive:{
                        0:{
                            items:2,
                            dots: true,
                            nav: false
                        },
                        767:{
                            items:6,
                            nav:true,
                            dots: false
                        }
                    }
                });
        });
    });


  </script>
