<?php
   $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
   $appState = $objectManager->get('\Magento\Framework\App\State');
   $registry = $objectManager->get('\Magento\Framework\Registry');
   $_product= $registry->registry('current_product');
   $price = $_product->getPrice();
   $productDescription= $_product->getShortDescription();
   ?>
<?php if (!empty($productDescription)){	?>
<div class="addtocart_tittle">
   <h2>Vehicle Compatibility</h2>
   <p><?php echo $productDescription; ?></p>
</div>
<?php
   }
   ?>