<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Magento\Customer\Block\Form\Login $block */
?>
<div class="block block-customer-login">
    <div class="block-title">
        <strong id="block-customer-login-heading" role="heading" aria-level="2"><?= $block->escapeHtml(__('Registered Customers')) ?></strong>
    </div>
    

    
    <div class="block-content" aria-labelledby="block-customer-login-heading">
        <form class="form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <fieldset class="fieldset login" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <div class="field note"><?= $block->escapeHtml(__('If you have an account, sign in with your email address.')) ?></div>
                <div class="field email required">
                    <label class="label" for="email"><span><?= $block->escapeHtml(__('Email')) ?></span></label>
                    <div class="control">
                        <input name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="input-text" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field password required">
                    <label for="pass" class="label"><span><?= $block->escapeHtml(__('Password')) ?></span></label>
                    <div class="control">
                        <input name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()) : ?> autocomplete="off"<?php endif; ?> class="input-text" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">
                    </div>
                </div>
                <?= $block->getChildHtml('form_additional_info') ?>
                <div class="actions-toolbar">
                    <div class="primary"><button type="submit" class="action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button></div>
                    <div class="primary"><a class="action " href="/checkout/"> <button type="button" class="action login primary" ><span><?= $block->escapeHtml(__('Guest Checkout')) ?></span></button></a></div>
                    <div class="secondary"><a class="action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a></div>

                </div>
            </fieldset>
        </form>
    </div>
</div>


<?php 
    $objectManager =  \Magento\Framework\App\ObjectManager::getInstance();        
    $storeManager  = $objectManager->get('\Magento\Store\Model\StoreManagerInterface');
    $storeID       = $storeManager->getStore()->getStoreId(); 
    $storeName     = $storeManager->getStore()->getName();
?>

<script src="https://tyresnmore.com/phonepe-js-sdk-master/bundle.js"></script>
<script>
require(['jquery','jquery/jquery.cookie'],
  function($){
    $('document').ready(function(){

     var date = new Date();
    var minutes = 15;
    date.setTime(date.getTime() + (minutes * 60 * 1000));


        var  storeID="<?=$storeID;?>";
        if(storeID==6){

        if($.cookie('phonepe')!=1){
        if($.cookie('phonepeLogin')!=1){
            $.cookie('phonepeLogin', '1',{expires: date});


        window.PhonePe.PhonePe.build(window.PhonePe.Constants.Species.web).then((sdk) => {
                        sdk.fetchAuthToken().then((res) => {


                          $.ajax({
                                type: 'POST',
                                url: '/phonepe/payment/accessToken',
                                data: {'grantToken':res.grantToken} ,
                                success: function (response) {


                                 if(response.cartItems){
                                    window.location.href='/checkout/';
                                 }else{
                                   window.location.href='/sales/order/history/';
                                 }

                                },
                                error: function (response) {



                                }
                            });


                        }).catch((err) => {




                        });


                });
        };

        };
        };

    });
});
</script>
