<?php
/**
 * @category   Clarksfield
 * @package    Clarksfield_Customersspeak
 * @author     nitish.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Clarksfield\Customersspeak\Block;

use Magento\Framework\View\Element\Template\Context;
use Clarksfield\Customersspeak\Model\CustomersspeakFactory;
/**
 * Customersspeak List block
 */
class CustomersspeakListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Customersspeak
     */
    protected $_customersspeak;
    public function __construct(
        Context $context,
        CustomersspeakFactory $customersspeak
    ) {
        $this->_customersspeak = $customersspeak;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Clarksfield Customersspeak Module List Page'));
        
        if ($this->getCustomersspeakCollection()) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'clarksfield.customersspeak.pager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getCustomersspeakCollection()
            );
            $this->setChild('pager', $pager);
            $this->getCustomersspeakCollection()->load();
        }
        return parent::_prepareLayout();
    }

    public function getCustomersspeakCollection()
    {
       $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 500000;

        $customersspeak = $this->_customersspeak->create();
        $collection = $customersspeak->getCollection();
       // $collection->addFieldToFilter('status','1');
        //$customersspeak->setOrder('customersspeak_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
        
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}