<?php
/**
 * @category   Tyres
 * @package    Tyres_Faq
 * @author     anuj95455@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tyres\Faq\Block;

use Magento\Framework\View\Element\Template\Context;
use Tyres\Faq\Model\FaqFactory;
/**
 * Faq List block
 */
class FaqListData extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Faq
     */
    protected $_faq;
    public function __construct(
        Context $context,
        FaqFactory $faq
    ) {
        $this->_faq = $faq;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        // $this->pageConfig->getTitle()->set(__('Tyres Faq Module List Page'));
       $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
       $cateId = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

	if (is_null($cateId)) {
        $cateId = 3161 ;
	}
        else {
	$cateId = $cateId->getId();

			}



        if ($this->getFaqCollection($cateId)) {
            $pager = $this->getLayout()->createBlock(
                'Magento\Theme\Block\Html\Pager',
                'tyres.faq.custompager'
            )->setAvailableLimit(array(5=>5,10=>10,15=>15))->setShowPerPage(true)->setCollection(
                $this->getFaqCollection($cateId)
            );
            $this->setChild('pager', $pager);
            $this->getFaqCollection($cateId)->load();
        }
        return parent::_prepareLayout();
    }

       public function getCategorylist($cateId){

        $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
        $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
            $connection = $resource->getConnection();

            $tableName = $resource->getTableName('tyres_faq');

            $sql = "Select * from `" . $tableName ."` where  category_ids LIKE '%".$cateId."%'";

           //  $data=$connection->fetchAll($sql);
                     $collection=$connection->fetchAll($sql);
         return $collection;
   }


    public function getFaqCollection($cateId)
    {
        $page = ($this->getRequest()->getParam('p'))? $this->getRequest()->getParam('p') : 1;
        $pageSize = ($this->getRequest()->getParam('limit'))? $this->getRequest()->getParam('limit') : 20000;

        $faq = $this->_faq->create();
        $collection = $faq->getCollection();
        $collection->addFieldToFilter('status','1');
	    $collection->addFieldToFilter('category_ids',['eq' =>$cateId]);
		//$collection->addFieldToFilter('category_ids',['like' => '%'.$cateId.'%']);
        //$faq->setOrder('faq_id','ASC');
        $collection->setPageSize($pageSize);
        $collection->setCurPage($page);

        return $collection;
    }

    public function getPagerHtml()
    {
        return $this->getChildHtml('pager');
    }
}
