<?php
/**
 * @category   Tyres
 * @package    Tyres_Faq
 * @author     anuj95455@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tyres\Faq\Block;

use Magento\Framework\View\Element\Template\Context;
use Tyres\Faq\Model\FaqFactory;
use Magento\Cms\Model\Template\FilterProvider;
/**
 * Faq View block
 */
class FaqView extends \Magento\Framework\View\Element\Template
{
    /**
     * @var Faq
     */
    protected $_faq;
    public function __construct(
        Context $context,
        FaqFactory $faq,
        FilterProvider $filterProvider
    ) {
        $this->_faq = $faq;
        $this->_filterProvider = $filterProvider;
        parent::__construct($context);
    }

    public function _prepareLayout()
    {
        $this->pageConfig->getTitle()->set(__('Tyres Faq Module View Page'));
        
        return parent::_prepareLayout();
    }

    public function getSingleData()
    {
        $id = $this->getRequest()->getParam('id');
        $faq = $this->_faq->create();
        $singleData = $faq->load($id);
        if($singleData->getFaqId() || $singleData['faq_id'] && $singleData->getStatus() == 1){
            return $singleData;
        }else{
            return false;
        }
    }
}