<fieldset class="fieldset create account" data-hasrequired="<?php /* @escapeNotVerified */ echo __('* Required Fields') ?>">
    <legend class="legend"><span><?php /* @escapeNotVerified */ echo __('Additional Information') ?></span></legend><br></p>
 
    <div class="field buyer_gst_number" data-container="change-buyer_gst_number">
        <label class="label" for="buyer_gst_number"><span><?php echo __('GST Number#') ?></span></label>
        <div class="control">
            <input type="text" name="buyer_gst_number" id="buyer_gst_number" autocomplete="buyer_gst_number" data-input="change-buyer_gst_number" title="<?php echo __('GST Number#') ?>" class="input-text" />
        </div>
    </div>
</fieldset>
