<?php
/**
 * @category   Tyres
 * @package    Tyres_Faq
 * @author     anuj95455@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Tyres\Faq\Controller\Adminhtml\Items;

class Save extends \Tyres\Faq\Controller\Adminhtml\Items
{
    public function execute()
    {
        if ($this->getRequest()->getPostValue()) {
            try {
                $model = $this->_objectManager->create('Tyres\Faq\Model\Faq');
                $data = $this->getRequest()->getPostValue();
                
                $objectManager = \Magento\Framework\App\ObjectManager::getInstance();


                $cat_name=array();
                foreach($data['category_ids'] as $categoryId){
                    //  print_r($categoryId); die();
                     $category = $objectManager->create('Magento\Catalog\Model\Category')->load($categoryId);
                     $cat_name[]=$category->getName();
                     
                }
                $category_name = implode(', ', $cat_name);
                $category_ids = implode(', ', $data['category_ids']);
                // print_r($category_name);
                // print_r($data); 
                
                $data['category']=$category_name;
                $data['category_ids']=$category_ids;
                
                

                if(isset($_FILES['image']['name']) && $_FILES['image']['name'] != '') {
                    try{
                        $uploaderFactory = $this->uploaderFactory->create(['fileId' => 'image']);
                        $uploaderFactory->setAllowedExtensions(['jpg', 'jpeg', 'gif', 'png']);
                        $imageAdapter = $this->adapterFactory->create();
                        $uploaderFactory->addValidateCallback('custom_image_upload',$imageAdapter,'validateUploadFile');
                        $uploaderFactory->setAllowRenameFiles(true);
                        $uploaderFactory->setFilesDispersion(true);
                        $mediaDirectory = $this->filesystem->getDirectoryRead($this->directoryList::MEDIA);
                        $destinationPath = $mediaDirectory->getAbsolutePath('tyres/faq');
                        $result = $uploaderFactory->save($destinationPath);
                        if (!$result) {
                            throw new LocalizedException(
                                __('File cannot be saved to path: $1', $destinationPath)
                            );
                        }
                        
                        $imagePath = 'tyres/faq'.$result['file'];
                        $data['image'] = $imagePath;
                    } catch (\Exception $e) {
                    }
                }
                if(isset($data['image']['delete']) && $data['image']['delete'] == 1) {
                    $mediaDirectory = $this->filesystem->getDirectoryRead($this->directoryList::MEDIA)->getAbsolutePath();
                    $file = $data['image']['value'];
                    $imgPath = $mediaDirectory.$file;
                    if ($this->_file->isExists($imgPath))  {
                        $this->_file->deleteFile($imgPath);
                    }
                    $data['image'] = NULL;
                }
                if (isset($data['image']['value'])){
                    $data['image'] = $data['image']['value'];
                }
                $inputFilter = new \Zend_Filter_Input(
                    [],
                    [],
                    $data
                );
                $data = $inputFilter->getUnescaped();
                $id = $this->getRequest()->getParam('id');
                if ($id) {
                    $model->load($id);
                    if ($id != $model->getId()) {
                        throw new \Magento\Framework\Exception\LocalizedException(__('The wrong item is specified.'));
                    }
                }
                
               // print_r($data); 
                
                
                
                
                $session = $this->_objectManager->get('Magento\Backend\Model\Session');
                $session->setPageData($model->getData());
                $model->setData($data);
                $model->save();
                
                
                if(!empty($category_ids)){
                $resource = $objectManager->get('Magento\Framework\App\ResourceConnection');
			    $connection = $resource->getConnection();
			    $tableName = $resource->getTableName('tyres_faq'); //gives table name with prefix
			    $sql = "Update " . $tableName . " Set category_ids = '".$category_ids."', category='".$category_name."' where faq_id ='".$model->getData('faq_id')."'";
			    //   echo $sql; die();
			    $connection->query($sql);
                }
                
                
                $this->messageManager->addSuccess(__('You saved the item.'));
                $session->setPageData(false);
                if ($this->getRequest()->getParam('back')) {
                    $this->_redirect('tyres_faq/*/edit', ['id' => $model->getId()]);
                    return;
                }
                $this->_redirect('tyres_faq/*/');
                return;
            } catch (\Magento\Framework\Exception\LocalizedException $e) {
                $this->messageManager->addError($e->getMessage());
                $id = (int)$this->getRequest()->getParam('id');
                if (!empty($id)) {
                    $this->_redirect('tyres_faq/*/edit', ['id' => $id]);
                } else {
                    $this->_redirect('tyres_faq/*/new');
                }
                return;
            } catch (\Exception $e) {
                $this->messageManager->addError(
                    __('Something went wrong while saving the item data. Please review the error log.')
                );
                $this->_objectManager->get('Psr\Log\LoggerInterface')->critical($e);
                $this->_objectManager->get('Magento\Backend\Model\Session')->setPageData($data);
                $this->_redirect('tyres_faq/*/edit', ['id' => $this->getRequest()->getParam('id')]);
                return;
            }
        }
        $this->_redirect('tyres_faq/*/');
    }
}
