<?php $_item = $block->getItem();
$_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
$priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
if (0) {
    $item_id = $_item->getData('item_id');
    $item = $_objectManager->get('Magento\Sales\Model\Order\Item')->getCollection();
    $item->addFieldToFilter('parent_item_id', $item_id);
    foreach ($item as $value) {
        $formattedPrice = $priceHelper->currency($value->getData('cgst_amount'), true, false);
        echo $formattedPrice;
    }
} else {
    $formattedPrice = $priceHelper->currency($_item->getData('cgst_amount'), true, false);
    echo $formattedPrice;
}
echo '<br>Rate:' . round($_item->getCgstPercent(), 2) . '%';

?>
