<?php
    $_item = $block->getItem();
    $_objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $priceHelper = $_objectManager->create('Magento\Framework\Pricing\Helper\Data'); // Instance of Pricing Helper
    $formattedPrice = $priceHelper->currency($_item->getData('utgst_amount'), true, false);
    echo $formattedPrice;
    echo '<br>Rate:' . round($_item->getUtgstPercent(), 2) . '%';
?>
