<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block \Magento\Catalog\Block\Product\View\Additional */
?>
<?php foreach ($block->getChildHtmlList() as $_html) :?>
    <?= /* @noEscape */ $_html ?>
<?php endforeach; ?>

<script type="application/ld+json">
{
  "@context": "https://schema.org",
  "@type": "FAQPage",
  "mainEntity": [{
    "@type": "Question",
    "name": "When should I change my car tyres ?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "A Tread wear indicator is a block of rubber (click to view) in the grooves of the tyre tread.If your tyre tread has worn out uptp or below indicator tyres should be changed.

In case your tyres have got any cuts or damage, uneven wearing out, bumps , you should change them.

In any case you should not use tyres beyond 5 years from the manufacturing year  indicated on the tyre even though they may look in good condition."
    }
  },{
    "@type": "Question",
    "name": "What is the size of the tyre for my car?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Go to the search panel above and input your car brand and model.You will get a list of models to choose from , click on your car model and you will reach the page with details of tyre sizes that fit in this car model.

Question: Is it safe to buy tyres online?

We don’t know about other online tyre sellers, but we are sure about tyresnmore.com – IT IS SAFE.

PAY ON DELIVERY , DOORSTEP FITMENT , HOME DELIVERY.

 To see TESTIMONIALS of verified purchasers of tyres from Tyresnmore.com ...read more"
    }
  },{
    "@type": "Question",
    "name": "Which is the best tyre for my car?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Go to the search panel above and input your car brand and model.

You will get a list of models to choose from , click on your car model and you will reach the page with details of features of best  tyres for your car."
    }
  },{
    "@type": "Question",
    "name": "How to take care of car tyres?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Get wheel alignment and balancing at least once a year or at every 5,000 kilometres , whichever is earlier.

Keep your tyres inflated at levels recommended by the car or bike manufacturer.

Drive carefully , so that you use your brakes only when required.

View details of Tyresnmore.com tyre service package. https://tyresnmore.com/all/tyre-care-service-packages"
    }
  },{
    "@type": "Question",
    "name": "Which is the cheapest tyre for my car?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "You will get a list of models to choose from , click on your car model and you will reach the page which features the cheapest  tyre for your car."
    }
  },{
    "@type": "Question",
    "name": "Can I get tyres fitted at home?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Tyresnmore.com gives doorstep fitment Bangalore , Delhi, Faridabad, Noida, Gurgaon and Hyderabad.

For all other cities we will ship the tyres to your address through FEDEX or another reliable courier."
    }
  },{
    "@type": "Question",
    "name": "When will my order for tyres reach my location?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "We have experts with tyre changing equipment in the Tyresnmore Vans and they will reach your location , in Hyderabad , Bangalore , Delhi NCR to change tyres at your doorstep.

Orders placed before 3 PM will be fulfilled today* Orders placed after 3 PM will be fulfilled tomorrow *The order fulfillment on same day is subject to availability of tyres in our warehouse. Our team will call you to fix an appointment for changing tyres at your location.

For cities other than those mentioned above , our tyre experts will inform you about the time of delivery and additional shipping charges if any."
    }
  },{
    "@type": "Question",
    "name": "How long does it take to change tyres?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Once our team reaches your location we need parking space for our van next to your vehicle , we have the equipment to change 1 tyre in 20 to 30 minutes and up to 4 tyres in 30 to 60 minutes"
    }
  },{
    "@type": "Question",
    "name": "What are the Payment options , can I pay on delivery or through EMIs?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "You can:

Pay on delivery *

Easy EMI available

Pay 100 % online now

*TnM reserves the right to ask for partial or full advance payment for any orders"
    }
  },{
    "@type": "Question",
    "name": "Will the tyre experts come to my location with debit/credit card machine , in case I am paying on delivery?",
    "acceptedAnswer": {
      "@type": "Answer",
      "text": "Yes the tyre experts will come with debit/credit card machine to your location to enable you to make payment,alternatively you can also pay via cash on delivery. Tyresnmore online private ltd. reserves the right to receive partial or full advance payment for any orders."
    }
  }]
}
</script>
