<?php
/**
 * @category   Clarksfield
 * @package    Clarksfield_Customersspeak
 * @author     nitish.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Clarksfield\Customersspeak\Model;

use Magento\Framework\Model\AbstractModel;

class Customersspeak extends AbstractModel
{
    /**
     * Define resource model
     */
    protected function _construct()
    {
        $this->_init('Clarksfield\Customersspeak\Model\ResourceModel\Customersspeak');
    }
}