<?php
/**
 * @category   Clarksfield
 * @package    Clarksfield_Customersspeak
 * @author     nitish.bluethink@gmail.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Clarksfield\Customersspeak\Controller\Index;

use Magento\Framework\App\Action\Context;
use Magento\Framework\Exception\NotFoundException;
use Clarksfield\Customersspeak\Block\CustomersspeakView;

class View extends \Magento\Framework\App\Action\Action
{
	protected $_customersspeakview;

	public function __construct(
        Context $context,
        CustomersspeakView $customersspeakview
    ) {
        $this->_customersspeakview = $customersspeakview;
        parent::__construct($context);
    }

	public function execute()
    {
    	if(!$this->_customersspeakview->getSingleData()){
    		throw new NotFoundException(__('Parameter is incorrect.'));
    	}
    	
        $this->_view->loadLayout();
        $this->_view->getLayout()->initMessages();
        $this->_view->renderLayout();
    }
}
