<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
?>
<p class="toolbar-amount" id="toolbar-amount">
    <?php
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $category = $objectManager->get('Magento\Framework\Registry')->registry('current_category');

    if(isset($category)){
        $path = $category->getPath();
        $ids = explode('/', $path);
    }

 //  if($category->getId()==3443){
//      if($category->getParentId()==3443){

        if($category && $ids[2]==3404){
        if ($block->getLastPageNum() > 1) {
        echo $block->escapeHtml(
            __(
                'Batteries  Found %1-%2 of %3',
                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
        ) ;
    } elseif ($block->getTotalNum() == 1) {
        echo $block->escapeHtml(
            __('%1 Battery Found', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        );
     }else {
        echo  $block->escapeHtml(
            __('%1 Batteries Found', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ;
    }

   }else{

    if ($block->getLastPageNum() > 1) :?>
        <?= $block->escapeHtml(
            __(
                'Tyres  Found %1-%2 of %3',
                '<span class="toolbar-number">' . $block->getFirstNum() . '</span>',
                '<span class="toolbar-number">' . $block->getLastNum() . '</span>',
                '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'
            ),
            ['span']
        ) ?>
    <?php elseif ($block->getTotalNum() == 1) :?>
        <?= $block->escapeHtml(
            __('%1 Tyre Found', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php else :?>
        <?= $block->escapeHtml(
            __('%1 Tyres Found', '<span class="toolbar-number">' . $block->getTotalNum() . '</span>'),
            ['span']
        ) ?>
    <?php endif;
   }
    ?>
</p>
<style type="text/css">
    .toolbar-products p#toolbar-amount {
    font-size: 23px!important;
    display: none;
}
</style>
